### PR TITLE
Escape all strings and add additional comments

### PR DESCRIPTION
**Pull request by FreddieAkeroyd**
See ISISComputingGroup/IBEX#4652

### CODE REVIEW

**Review by DominicOram — CHANGES_REQUESTED** [review]
Code works and documentation is much better, thank you. Doing this ticket highlighted that there is a lot of duplicate code between the stuff using CLI and conventional arguments. Can you instead refactor it to put the common stuff into a method?

**Comment by FreddieAkeroyd** [comment]
I only put the non-CLI stuff in there so it would compile on VS2010, I didn't think it was worth creating a separate library as we should be updating compiler in the near future. We could just remove the vs2010 code and only compile on later Visual studio, or add a separate ticket to remove the code after the compiler update.

**Comment by FreddieAkeroyd** [comment]
Actually, you were more suggesting to put the non-cli stuff into a method. That seems fair, i only didn't do that as i planned to remove the other stuff and then there would be an extra method call left over. But that is not too bad. However I'm tempted to remove the VS2010 stuff though as it looks horrible...

**Comment by DominicOram** [comment]
Yh, I see why it's there. I think:
* Move non-cli stuff to a method
* Add ticket to remove code when we change VS version

**Comment by FreddieAkeroyd** [comment]
The VS2010 code was not a full/proper implementation i.e. it just did 3 positional arguments and none of the other options. I though it was cleanest just to remove the 2010 implementation, if we need to run the code on an instrument we can just copy a static VS2017 build from jenkins

**Review by DominicOram — APPROVED** [review]
I've added a note about VS2010/2017 to https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/TestSerialPort. Code looks good, thank you.

**Pull request merged**
